# Generated by Django 4.2.17 on 2024-12-10 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pollution_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monitoring_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='rivers.river')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measurement_date', models.DateField()),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='rivers.river')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='rivers.monitoringstation')),
            ],
        ),
        migrations.CreateModel(
            name='EcologicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('river', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='rivers.river')),
            ],
        ),
    ]
