# Generated by Django 4.2.17 on 2024-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen', models.FloatField()),
                ('biological_index', models.FloatField()),
                ('pollutant_concentration', models.FloatField()),
                ('temperature', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
