# Generated by Django 4.2.17 on 2024-12-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rivers", "0002_sensordata"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringstation",
            name="latitude",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name="monitoringstation",
            name="longitude",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name="river",
            name="latitude",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
        migrations.AddField(
            model_name="river",
            name="longitude",
            field=models.DecimalField(decimal_places=10, default=0, max_digits=13),
        ),
    ]
